
title = "pubsub config"

[topics]
  [topics.rabbitmq]
    name = "go.micro.topic.rabbitmq.notice"

  [topics.redis]
    name = "go.micro.topic.redis.notice"


[rabbitmq]
server = "192.168.1.101"
ports = [ 8001, 8001, 8002 ]
username = "guest"
password = "guest"
amqp = "amqp://guest:guest@192.168.0.101:5672"

[services]
  [services.rabbitmq]
    name = "go.micro.srv.rabbitmq.demo"
    info = "rabbitmq service"

  [servers.redis]
    name = "go.micro.srv.redis.name"
    info = "redis service name"